# -*- coding: utf-8 -*-
{
    "name": "HR Holiday Attendance Views",
    "version": "18.0.1.0.0",
    "category": "Tools",
    "summary": "HR Holiday Attendance Customization",
    "description": " This module customizes the views for HR holiday attendance, including late forms and worked days.",
    "author": 'GonzaOdoo',
    "maintainer": "GonzaOdoo",
    "website": 'https://www.yourcompany.com',
    "depends": ['hr_holidays','hr_payroll_attendance'],
    "data":['views/views.xml','views/ips_views.xml',
            'views/report_wizard.xml',
            'views/report_templates.xml',
            'views/report_templates_holiday.xml',
            'views/report_templates_bonus.xml',
            'views/report_assistance.xml',
            'views/hr_allocations_views.xml',
            'views/attendance_views.xml',
            'security/ir.model.access.csv'],
    "assets": {},
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True
}